server:
  port: 8089
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
#Way to making spring web app to standalone either thorugh fluent builder api or the below config
#spring:
  #main:
    #web-application-type: none