server:
  port: 8889
spring:
  application:
    name: tatamotors-configserver
  cloud:
    config:
      server:
        git:
          uri: https://abinashmishraby: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@github.com/abinashmishraby/tatamotors-configrepo.git
          refresh-rate: 120
  security:
    user:
      name: configadmin
      password: welcome1
      roles:
      - administration

